# constants.py - Oyun sabitleri

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 720
FPS = 60
TILE_SIZE = 64

# Oyuncu Fizik
PLAYER_ACCELERATION = 1.2
PLAYER_FRICTION = 0.85
PLAYER_AIR_RESISTANCE = 0.95
PLAYER_GRAVITY = 0.8
PLAYER_JUMP_SPEED = -18
PLAYER_MAX_FALL_SPEED = 12
PLAYER_MAX_HEALTH = 6
PLAYER_KNOCKBACK_FORCE = 15
COYOTE_TIME = 0.1
JUMP_BUFFER_TIME = 0.1
ANIMATION_SPEED = 0.2
HIT_COOLDOWN = 1000
ATTACK_DURATION = 300

# Düşman
ENEMY_NORMAL_SPEED = 3
ENEMY_NORMAL_HEALTH = 30
ENEMY_NORMAL_DAMAGE = 1
ENEMY_NORMAL_SCORE = 200
ENEMY_STRONG_SPEED = 5
ENEMY_STRONG_HEALTH = 80
ENEMY_STRONG_DAMAGE = 2
ENEMY_STRONG_SCORE = 500
ENEMY_FLYING_SPEED = 2
ENEMY_FLYING_HEALTH = 40
ENEMY_FLYING_DAMAGE = 1
ENEMY_FLYING_SCORE = 300
ENEMY_FLYING_VERTICAL_SPEED = 1.5
ENEMY_FLYING_VERTICAL_DISTANCE = 100
ENEMY_SHOOTER_SPEED = 1
ENEMY_SHOOTER_HEALTH = 50
ENEMY_SHOOTER_DAMAGE = 1
ENEMY_SHOOTER_SCORE = 350
ENEMY_SHOOT_INTERVAL = 120
ENEMY_PATROL_DISTANCE = 120
ENEMY_HIT_EFFECT_DURATION = 200
ENEMY_ANIMATION_SPEED = 0.15

# Mermi
PROJECTILE_SPEED = 6
PROJECTILE_DAMAGE = 1
PROJECTILE_LIFETIME = 180
PROJECTILE_WIDTH = 16
PROJECTILE_HEIGHT = 8

# Platform
PLATFORM_DEFAULT_DISTANCE = 128
PLATFORM_DEFAULT_SPEED = 2
PLATFORM_VERTICAL_DISTANCE = 96

# Tuzak
SPIKE_DAMAGE = 1
SAW_DAMAGE = 2

# Parçacık
PARTICLE_JUMP_COUNT = 5
PARTICLE_COIN_COUNT = 8
PARTICLE_HIT_COUNT = 6
PARTICLE_ENEMY_DEATH_COUNT = 12
PARTICLE_DEFAULT_LIFETIME = 30
PARTICLE_GRAVITY = 0.5

# Skor
COIN_SCORE = 50

# Renk
COLOR_SKY_BLUE = '#87ceeb'
COLOR_BROWN = '#8B7355'
COLOR_DARK_BROWN = '#654321'
COLOR_GOLD = '#FFD700'
COLOR_RED = '#ff0000'
COLOR_PURPLE = '#9b59b6'
COLOR_ORANGE_RED = '#e74c3c'
COLOR_PROJECTILE_RED = '#ff6b6b'
COLOR_DUST_BROWN = '#d4a574'
COLOR_WHITE = '#ffffff'
COLOR_BLACK = '#000000'
COLOR_GRAY = '#888888'

# UI
UI_HEART_SIZE = 48
UI_HEART_START_X = 20
UI_HEART_START_Y = 70

# Kamera
CAMERA_LERP_SPEED = 0.1
